import { Goal, StickyNote, Task, TempoTab } from "./types";

/** Tailwind class sets for agenda blocks by course/category (pastel red / blue / green / yellow). */
export function categoryBlockClasses(category: string): string {
  const c = category.toUpperCase();
  if (c.includes("4284") || c.includes("OS"))
    return "bg-[#ffd6d6] border-[#f5a8a8] text-[#5c2020]";
  if (c.includes("3114") || c.includes("DATA") || c.includes("SQL"))
    return "bg-[#cfe8ff] border-[#9dc4f0] text-[#143a5c]";
  if (c.includes("4924")) return "bg-[#ede9fe] border-[#c4b5fd] text-[#3b2c5c]";
  if (c.includes("3724")) return "bg-[#fce7f3] border-[#f0abfc] text-[#5c1d42]";
  if (c.includes("BIT") || c.includes("4904")) return "bg-[#d1fae5] border-[#6ee7b7] text-[#134e4a]";
  if (c.includes("PHYS")) return "bg-[#d4f4dd] border-[#9dd4ae] text-[#1e4d2b]";
  return "bg-[#fff3c4] border-[#e8d58a] text-[#5c4a14]";
}

// Defines the main navigation tabs used throughout the Tempo dashboard.
export const tempoTabs: TempoTab[] = [
  "Dashboard",
  "Active Tasks",
  "Archive",
  "Reminders",
  "Goals",
  "Focus",
  "Export",
];

/** Virginia Tech VT mock workload — eleven blocks covering Mon Apr 27 → Sun May 3, 2026. */
export const initialTasks: Task[] = [
  {
    id: 1,
    title: "CS3114: Indexes & hashing study block",
    category: "CS3114",
    description: "Textbook §18 + practice problems before Thursday quiz.",
    date: "2026-04-27",
    startHour: 9,
    durationMinutes: 90,
    deadline: "2026-05-02",
    subjectivePriority: 4,
    status: "In Progress",
    archived: false,
    archivedAt: null,
    archiveReason: null,
  },
  {
    id: 2,
    title: "CS4924: Capstone milestone check-in notes",
    category: "CS4924",
    description: "Draft bullet list for advisor meeting slide deck.",
    date: "2026-04-27",
    startHour: 15,
    durationMinutes: 60,
    deadline: "2026-05-06",
    subjectivePriority: 5,
    status: "Not Started",
    archived: false,
    archivedAt: null,
    archiveReason: null,
  },
  {
    id: 3,
    title: "BIT4904: Standup & sprint backlog",
    category: "BIT4904",
    description: "Update board and unblock integration tasks.",
    date: "2026-04-28",
    startHour: 11,
    durationMinutes: 45,
    deadline: "2026-05-01",
    subjectivePriority: 4,
    status: "In Progress",
    archived: false,
    archivedAt: null,
    archiveReason: null,
  },
  {
    id: 4,
    title: "CS3724: Scheduling algorithms reading",
    category: "CS3724",
    description: "SRTF vs FCFS worksheet for Wednesday discussion.",
    date: "2026-04-28",
    startHour: 19,
    durationMinutes: 75,
    deadline: "2026-05-03",
    subjectivePriority: 3,
    status: "Not Started",
    archived: false,
    archivedAt: null,
    archiveReason: null,
  },
  {
    id: 5,
    title: "CS3114: SQL tuning lab continuation",
    category: "CS3114",
    description: "EXPLAIN ANALYZE write-up stub for lab report.",
    date: "2026-04-29",
    startHour: 13,
    durationMinutes: 120,
    deadline: "2026-05-04",
    subjectivePriority: 4,
    status: "Not Started",
    archived: false,
    archivedAt: null,
    archiveReason: null,
  },
  {
    id: 6,
    title: "CS4924: Prototype wiring + smoke test block",
    category: "CS4924",
    description: "Run happy-path demo on laptops before filming.",
    date: "2026-04-30",
    startHour: 10,
    durationMinutes: 150,
    deadline: "2026-05-08",
    subjectivePriority: 5,
    status: "In Progress",
    archived: false,
    archivedAt: null,
    archiveReason: null,
  },
  {
    id: 7,
    title: "CS3724: Virtual memory worksheet",
    category: "CS3724",
    description: "Page tables + TLB exercise set.",
    date: "2026-05-01",
    startHour: 14,
    durationMinutes: 90,
    deadline: "2026-05-05",
    subjectivePriority: 3,
    status: "Not Started",
    archived: false,
    archivedAt: null,
    archiveReason: null,
  },
  {
    id: 8,
    title: "BIT4904: Stakeholder demo dry run",
    category: "BIT4904",
    description: "10-minute rehearsal; time each section.",
    date: "2026-05-01",
    startHour: 16,
    durationMinutes: 40,
    deadline: "2026-05-07",
    subjectivePriority: 4,
    status: "Not Started",
    archived: false,
    archivedAt: null,
    archiveReason: null,
  },
  {
    id: 9,
    title: "CS3114: Quiz review session",
    category: "CS3114",
    description: "Flash cards + past exam questions.",
    date: "2026-05-02",
    startHour: 8,
    durationMinutes: 60,
    deadline: "2026-05-02",
    subjectivePriority: 5,
    status: "In Progress",
    archived: false,
    archivedAt: null,
    archiveReason: null,
  },
  {
    id: 10,
    title: "CS4924: Code review + refactor window",
    category: "CS4924",
    description: "Address PR comments from teammate.",
    date: "2026-05-03",
    startHour: 12,
    durationMinutes: 90,
    deadline: "2026-05-09",
    subjectivePriority: 4,
    status: "Not Started",
    archived: false,
    archivedAt: null,
    archiveReason: null,
  },
  {
    id: 11,
    title: "CS3724: Deadlock proofs practice",
    category: "CS3724",
    description: "Two exam-style deadlock detection problems.",
    date: "2026-05-03",
    startHour: 17,
    durationMinutes: 60,
    deadline: "2026-05-06",
    subjectivePriority: 3,
    status: "Not Started",
    archived: false,
    archivedAt: null,
    archiveReason: null,
  },
];

export const initialStickyNotes: StickyNote[] = [];

export const initialGoals: Goal[] = [];